"""update 'updateTask' to nullable

Revision ID: 27a483e022a5
Revises: 7a11f3fc1a3c
Create Date: 2024-11-26 20:28:00.651895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a483e022a5'
down_revision: Union[str, None] = '7a11f3fc1a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Task',
        'updateAt',
        existing_type=sa.DateTime(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
