"""change Task schema - status column to Enum

Revision ID: 8001d9a89cf2
Revises: 27a483e022a5
Create Date: 2024-11-28 19:15:35.516391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8001d9a89cf2'
down_revision: Union[str, None] = '27a483e022a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

todo_enum = sa.Enum('todo', 'in-progress', 'done', name='Todo_enum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    todo_enum.create(op.get_bind(), checkfirst=True)
    op.execute(
        """
        ALTER TABLE "Task"
        ALTER COLUMN "status"
        TYPE "Todo_enum"
        USING "status"::"Todo_enum";
        """
    )
   # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        ALTER TABLE "Task"
        ALTER COLUMN "status"
        TYPE VARCHAR
        USING "status"::TEXT;
        """
    )
    # 刪除 ENUM 類型
    todo_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
